services:
  app:
    build: .
    container_name: insta-clone
    ports:
      - "8000:8000"
    environment:
       MONGO_URI: ${MONGO_URI}
       SECRET_KEY: ${SECRET_KEY}
       API_KEY: ${API_KEY}
       API_SECRET: ${API_SECRET}
       CLOUD_NAME: ${CLOUD_NAME}
       URL: "https://instagram-clone-3-cfe5.onrender.com"
    networks:
      - app_network

networks:
  app_network: